apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-migration-connection
  namespace: reporting
spec:
  encryptedData:
    db: AgBOWi0FX14Wo1oevYb+UmYVczbrKApTS2G7n3Q2Yo1a3u1GmJIi8FEYnM3N+x+jwiDBwjKMXa9XPsWeBpJ5unzc3088nQ+4dCTMJK2PZ47oC+C8V29ef1Z39ozolJ5WFkkyDrYyJ7hcRjgn7r96UG9ClUvUqJl/igJnyY2wNiSIKVlsjjmDtoUbIz+08fLv5fj4I+ssXDfOCr4RD4MdcVPHEqUAqVLzzMQPoqt67LtNh7m3nzhx7PUbh6JimFz6bsJJR5YJJ2mgIOvk8R19IEvJutmmZmj7rI95sCCcAXKyzBWJpYHMdbk3lMmakniQuz9LVtz1Ojjm85FjXWMuKNSCfS0yBestXHB/21pZs99mh924tzbqw+j/XgBXHk4oiReerRWRqDmZYV+AoPoXQLPLEz6TD2f/liA14dyf4CvvIWOn5B16TEjg2OmJyHImhQCYgDHpNlTqrwcRTAO9br95//Y5uGcONmQ/sFfs8JNuaiUHQaTJ3C5bhpMCm8b9QmVfZimrrhz5/2qHPy+QwGby/7QfbR/nvTL4Xj7FcnoIMSLUwheTCQF5uI1BoDFKGowgCtQ22GS2D9RrrnWkxBWiO+5izrrue8dMLQydrNVnir8vN9WHvM0lxfkYVyALaRGMJQa2fLqAJZ2xTIzZf74Hk6MCwkoe9oF2jPlf9QkCYn8huViAqkMehLqJYBUNUISvQ3JQ1usIcgfpd+dR3E3d7T/uWiZnh75aYTmzsYqFsE5Cx+x1vfTcqkiWv5xse1jt5XsLTejQwpf6aoKF0G6pUVIDko3fX/O7Yi/rApmZlgQ7GoEbreMYqn5ftk63kQ5lWxYO6bdKDfYxwBY3b4UHum4Tu8oBtRgMhMVu8EgYIKLqtztr9Pd6+WCYt4Y58MBwkLcZEPaOZQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: database-migration-connection
      namespace: reporting

