apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-reporting-api
  namespace: reporting
spec:
  prefix: /reporting/
  service: treetracker-reporting-api-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    origins:
      - https://admin.treetracker.org
      - https://staging-admin.treetracker.org
    methods: GET, OPTIONS
    headers:
    - Content-Type
    - Authorization
