apiVersion: apps/v1
kind: Deployment
metadata:
  name: tretracker-reporting-api
  labels:
    app: treetracker-reporting-api 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tretracker-reporting-api
  template:
    metadata:
      labels:
        app: tretracker-reporting-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool
      containers:
      - name: tretracker-reporting-api
        image: greenstand/tretracker-reporting:TAG
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: dbconnection
                key: database
