apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: tretracker-reporting-be-api
spec:
  prefix: /reporting/
  service: treetracker-reporting-api-ambassador-svc
  rewrite: /
  timeout_ms: 0
  cors:
    methods: GET, OPTIONS
    headers:
    - Content-Type
    - Authorization
