apiVersion: v1
kind: Service
metadata:
  name: treetracker-reporting-api-ambassador-svc
  labels:
    app: treetracker-reporting-api
    name: treetracker-reporting-api-ambassador-svc
  namespace: reporting
spec:
  selector:
    app: treetracker-reporting-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3006
